### PR TITLE
add example tests

### PR DESCRIPTION
**Pull request by phpnode**
It wasn't really obvious how to write tests for a plugin so here's an example that hopefully other people will find helpful.

### CODE REVIEW

**Comment by sebmck** [comment]
Hm, not sure. I've been thinking about exposing the internal babel test harness so you could just run `$ babel-test` or something and I'm not sure I want to encourage a specific pattern until then.

**Comment by phpnode** [comment]
@sebmck have you tried writing any standalone plugins yourself yet? The development process is surprisingly tricky, I'm struggling to get https://github.com/codemix/babel-plugin-typecheck + tests working with the latest release and I seem to get race conditions with `require()`.

**Comment by sebmck** [comment]
@phpnode How are you getting race conditions with `require()`?

**Comment by phpnode** [comment]
@sebmck I'd ideally like to run the tests with the plugin enabled, so that I can verify the typechecking in the tests themselves (as the tests are compiled with babel anyway). However it doesn't seem to be possible to load a plugin from a filename, only via `node_modules`. Digging a little deeper it looks like it happens because the plugin file gets `require`'d *while* `babel/register` is running, and therefore `require` returns an empty object rather than the exported plugin function.

I think plugins are an exceptionally cool part of babel. Having now played with them a bit I think they are actually much, much nicer than macros ala sweet.js which do get very complicated quickly. I'd really like to help with tutorials / documentation around this feature, and help make it as easy as possible for people to get started, and that includes tests, hence this PR.

I'm not quite sure how the babel-test integration would work for plugins?

**Comment by sebmck** [comment]
@phpnode

> I'd really like to help with tutorials / documentation around this feature, and help make it as easy as possible for people to get started, and that includes tests, hence this PR.

Awesome! The [plugin docs](http://babeljs.io/docs/usage/plugins/) could **really** be fleshed out more so any help in that process would be amazing. Would you be interested in writing a more elaborate plugin example repo that I can just point people towards? The extremely minimal example plugin in this repo isn't really helpful and doesn't really show any of the actual plugin API.

**Comment by phpnode** [comment]
@sebmck yes absolutely, although I wonder if it's better to use a few different plugins as examples as there is a balance between making something simple enough to understand quickly and being so trivial as to be not really helpful. I wrote typecheck partially to help illustrate how easy plugins can be, at ~400 lines it should still be reasonably easy to follow - https://github.com/codemix/babel-plugin-typecheck/blob/master/src/index.js

**Pull request closed without merging**
